import type { Metadata } from "next";
import { geistMono, geistSans } from "@/config/fonts";
import { Toaster } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Orejitas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
